name: Add new link
description: You would like to add a new link to the collection
labels: ["new link"]
body:

  - type: input
    id: link
    attributes:
      label: URL of the article or video
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: >
        Explain the motivation for adding this link to the current collection.
      placeholder: |
        This new link should be added because...
    validations:
      required: true

  - type: checkboxes
    id: affiliation
    attributes:
      label: Affiliation
      description: >
        Please indicate how you are associated with the new proposed content.
      options:
        - label: "I am the author of the article or project"
        - label: "I am working for/with the company which is publishing the article or project"
        - label: "I'm just stumbled upon this and have to affiliation"
    validations:
      required: true
